# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-SQL-Abstract
version:      0.07
version_from: lib/DBIx/SQL/Abstract.pm
installdirs:  site
requires:
    DBI:                           0
    SQL::Abstract:                 1.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
